#!/bin/bash

module load python/3.10
python3.10 -m venv .venv
source .venv/bin/activate
python3.10 -m pip install --upgrade pip
python3.10 -m pip install wheel==0.43.0
python3.10 -m pip install -r ../requirements.txt
deactivate
uuid=`uuidgen`
sed -e "s/\"UUID\"/\"${uuid::8}\"/" config-in.json > config-${uuid::8}.json
sed -e "s/UUID/${uuid::8}/" sbatch-in.sh > sbatch.sh
sbatch sbatch.sh
module unload python/3.10
